import { Question } from '@/types/game';
import { texifyQuestionFields } from '@/lib/math/texify';

export const QUESTION_BANK: Question[] = [
  // ========== 복소수 개념 ==========
  {
    id: 'c001',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '허수 단위 i를 정의할 때, i²의 값은?',
    options: ['-1', '1', 'i', '-i'],
    answer: '-1',
    explanation: 'i는 i²=-1을 만족하는 수로 정의한다.',
  },
  {
    id: 'c002',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '다음 중 허수인 것은?',
    options: ['√4', '√(-9)', '√9', '0'],
    answer: '√(-9)',
    explanation: '√(-9) = 3i이므로 허수이다.',
  },
  {
    id: 'c003',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '복소수 a+bi에서 실수부분은?',
    options: ['a', 'b', 'bi', 'a+bi'],
    answer: 'a',
    explanation: '복소수 a+bi에서 a를 실수부분, b를 허수부분이라 한다.',
  },
  {
    id: 'c004',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '복소수 3-5i의 켤레복소수는?',
    options: ['3+5i', '-3+5i', '-3-5i', '3-5i'],
    answer: '3+5i',
    explanation: '복소수 a+bi의 켤레복소수는 a-bi이다.',
  },
  {
    id: 'c005',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '다음 중 순허수인 것은?',
    options: ['2+3i', '3i', '3', '0'],
    answer: '3i',
    explanation: '순허수는 실수부분이 0이고 허수부분이 0이 아닌 복소수이다.',
  },
  {
    id: 'c006',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: 'i³의 값은?',
    options: ['-i', 'i', '-1', '1'],
    answer: '-i',
    explanation: 'i³ = i²·i = (-1)·i = -i',
  },
  {
    id: 'c007',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: 'i⁴의 값은?',
    options: ['1', '-1', 'i', '-i'],
    answer: '1',
    explanation: 'i⁴ = (i²)² = (-1)² = 1',
  },
  {
    id: 'c008',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: 'i¹⁰의 값은?',
    options: ['-1', '1', 'i', '-i'],
    answer: '-1',
    explanation: 'i¹⁰ = (i⁴)²·i² = 1·(-1) = -1',
  },
  {
    id: 'c009',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: 'i²⁰²⁵의 값은?',
    options: ['i', '-i', '1', '-1'],
    answer: 'i',
    explanation: '2025 = 4×506 + 1이므로 i²⁰²⁵ = i¹ = i',
  },
  {
    id: 'c010',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '두 복소수가 서로 같을 조건: a+bi = c+di일 때 옳은 것은?',
    options: ['a=c, b=d', 'a=d, b=c', 'a+b=c+d', 'a²+b²=c²+d²'],
    answer: 'a=c, b=d',
    explanation: '복소수가 같으면 실수부분끼리, 허수부분끼리 같다.',
  },
  {
    id: 'c011',
    type: 'multiple',
    category: 'complex',
    difficulty: 1,
    text: '(3+2i) + (1-4i)를 계산하면?',
    options: ['4-2i', '4+6i', '2+6i', '2-2i'],
    answer: '4-2i',
    explanation: '(3+1) + (2-4)i = 4-2i',
  },
  {
    id: 'c012',
    type: 'multiple',
    category: 'complex',
    difficulty: 1,
    text: '(5+3i) - (2+7i)를 계산하면?',
    options: ['3-4i', '3+4i', '7+10i', '7-4i'],
    answer: '3-4i',
    explanation: '(5-2) + (3-7)i = 3-4i',
  },
  {
    id: 'c013',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: '(2+i)(3-2i)를 계산하면?',
    options: ['8-i', '4+i', '8+i', '4-i'],
    answer: '8-i',
    explanation: '6-4i+3i-2i² = 6-i+2 = 8-i',
  },
  {
    id: 'c014',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: '(1+i)²를 계산하면?',
    options: ['2i', '2', '1+2i', '-2i'],
    answer: '2i',
    explanation: '1+2i+i² = 1+2i-1 = 2i',
  },
  {
    id: 'c015',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: '(1+i)(1-i)를 계산하면?',
    options: ['2', '0', '1+i²', '2i'],
    answer: '2',
    explanation: '1-i² = 1-(-1) = 2',
  },
  {
    id: 'c016',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: '(2+3i)/(1+i)를 계산하면?',
    options: ['(5+i)/2', '5/2+i/2', '(5-i)/2', '(1+5i)/2'],
    answer: '(5+i)/2',
    explanation: '(2+3i)(1-i)/((1+i)(1-i)) = (2-2i+3i-3i²)/2 = (2+i+3)/2 = (5+i)/2',
  },
  {
    id: 'c017',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: '1/(1+i)를 계산하면?',
    options: ['(1-i)/2', '(1+i)/2', '1/2-i/2', '이와 같다: 1-i'],
    answer: '(1-i)/2',
    explanation: '(1-i)/((1+i)(1-i)) = (1-i)/2',
  },
  {
    id: 'c018',
    type: 'short',
    category: 'complex',
    difficulty: 1,
    text: '√(-4)를 $i$를 사용하여 나타낼 때, $i$의 계수(정수)는?',
    answer: '2',
    explanation: '√(-4) = 2i 이므로 계수는 2',
  },
  {
    id: 'c019',
    type: 'short',
    category: 'complex',
    difficulty: 2,
    text: '(2+i) + (1-3i)의 실수부분은?',
    answer: '3',
    explanation: '(2+1) + (1-3)i = 3-2i이므로 실수부분은 3',
  },
  {
    id: 'c020',
    type: 'short',
    category: 'complex',
    difficulty: 2,
    text: '(3+2i)(3-2i)의 값은?',
    answer: '13',
    explanation: '9-4i² = 9+4 = 13',
  },
  {
    id: 'c021',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '복소수 z = a+bi에 대해 z = z̄ (켤레복소수)가 성립할 조건은?',
    options: ['b=0 (실수)', 'a=0 (순허수)', 'a=b', 'a=1'],
    answer: 'b=0 (실수)',
    explanation: 'z = a+bi, z̄ = a-bi이므로 z = z̄ ⟺ b=0',
  },
  {
    id: 'c022',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: 'z·z̄는 어떤 수인가? (z = a+bi)',
    options: ['항상 음이 아닌 실수', '항상 양의 실수', '허수', '0'],
    answer: '항상 음이 아닌 실수',
    explanation: 'z·z̄ = (a+bi)(a-bi) = a²+b² ≥ 0',
  },

  // ========== 이차방정식 개념 ==========
  {
    id: 'q001',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '이차방정식 ax²+bx+c=0의 판별식 D는?',
    options: ['b²-4ac', 'b²+4ac', '4ac-b²', '√(b²-4ac)'],
    answer: 'b²-4ac',
    explanation: '판별식 D = b²-4ac',
  },
  {
    id: 'q002',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: 'D>0이면 이차방정식의 근은?',
    options: ['서로 다른 두 실근', '중근', '서로 다른 두 허근', '근 없음'],
    answer: '서로 다른 두 실근',
    explanation: 'D>0이면 서로 다른 두 실근을 가진다.',
  },
  {
    id: 'q003',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: 'D=0이면 이차방정식의 근은?',
    options: ['중근 (같은 두 실근)', '서로 다른 두 실근', '두 허근', '근 없음'],
    answer: '중근 (같은 두 실근)',
    explanation: 'D=0이면 중근을 가진다.',
  },
  {
    id: 'q004',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: 'D<0이면 이차방정식의 근은?',
    options: ['서로 다른 두 허근', '서로 다른 두 실근', '중근', '실근과 허근 각 하나'],
    answer: '서로 다른 두 허근',
    explanation: 'D<0이면 서로 켤레인 두 허근을 가진다.',
  },
  {
    id: 'q005',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '이차방정식 x²+bx+c=0의 두 근을 α, β라 할 때, α+β는?',
    options: ['-b', 'b', 'c', '-c'],
    answer: '-b',
    explanation: '근과 계수의 관계: α+β = -b/1 = -b',
  },
  {
    id: 'q006',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '이차방정식 x²+bx+c=0의 두 근을 α, β라 할 때, αβ는?',
    options: ['c', '-c', 'b', '-b'],
    answer: 'c',
    explanation: '근과 계수의 관계: αβ = c/1 = c',
  },
  {
    id: 'q007',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '이차방정식 2x²-3x+1=0의 두 근의 합은?',
    options: ['3/2', '-3/2', '1/2', '3'],
    answer: '3/2',
    explanation: '두 근의 합 = -(-3)/2 = 3/2',
  },
  {
    id: 'q008',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '이차방정식 2x²-3x+1=0의 두 근의 곱은?',
    options: ['1/2', '-1/2', '3/2', '1'],
    answer: '1/2',
    explanation: '두 근의 곱 = 1/2',
  },
  {
    id: 'q009',
    type: 'multiple',
    category: 'concept',
    difficulty: 3,
    text: '두 수 2, 3을 근으로 하는 x²의 계수가 1인 이차방정식은?',
    options: ['x²-5x+6=0', 'x²+5x+6=0', 'x²-5x-6=0', 'x²+5x-6=0'],
    answer: 'x²-5x+6=0',
    explanation: '합=5, 곱=6이므로 x²-5x+6=0',
  },

  // ========== 이차방정식 풀기 (인수분해) ==========
  {
    id: 'q010',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²-5x+6=0의 두 근의 합은?',
    answer: '5',
    explanation: '(x-2)(x-3)=0이므로 x=2 또는 x=3, 합=5',
  },
  {
    id: 'q011',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²-5x+6=0의 두 근의 곱은?',
    answer: '6',
    explanation: '(x-2)(x-3)=0이므로 x=2, x=3, 곱=6',
  },
  {
    id: 'q012',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²-4=0의 양의 근은?',
    answer: '2',
    explanation: '(x-2)(x+2)=0이므로 x=2 또는 x=-2',
  },
  {
    id: 'q013',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²+3x+2=0의 두 근의 합은?',
    answer: '-3',
    explanation: '(x+1)(x+2)=0이므로 x=-1 또는 x=-2, 합=-3',
  },
  {
    id: 'q014',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: '2x²-7x+3=0의 두 근 중 더 큰 정수 근은?',
    answer: '3',
    explanation: '(2x-1)(x-3)=0이므로 x=1/2 또는 x=3, 정수 근은 3',
  },
  {
    id: 'q015',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x(x-3)=0의 두 근 중 양의 근은?',
    answer: '3',
    explanation: 'x=0 또는 x=3',
  },
  {
    id: 'q016',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: '(x-2)²=0의 근은?',
    answer: '2',
    explanation: '중근 x=2',
  },
  {
    id: 'q017',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²-9=0의 양의 근은?',
    answer: '3',
    explanation: '(x-3)(x+3)=0이므로 x=3 또는 x=-3',
  },
  {
    id: 'q018',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+2x-8=0의 두 근의 곱은?',
    answer: '-8',
    explanation: '(x+4)(x-2)=0, 두 근의 곱 = -8',
  },

  // ========== 이차방정식 풀기 (근의 공식, 허근 포함) ==========
  {
    id: 'q020',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-2x+5=0의 두 근은?',
    options: ['1±2i', '-1±2i', '2±i', '1±√5'],
    answer: '1±2i',
    explanation: 'D=4-20=-16<0, x=(2±√(-16))/2 = (2±4i)/2 = 1±2i',
  },
  {
    id: 'q021',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+4=0의 두 근은?',
    options: ['±2i', '±2', '±4i', '±√2·i'],
    answer: '±2i',
    explanation: 'x²=-4이므로 x=±2i',
  },
  {
    id: 'q022',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+x+1=0의 두 근은?',
    options: ['(-1±√3·i)/2', '(1±√3·i)/2', '(-1±√5)/2', '±i'],
    answer: '(-1±√3·i)/2',
    explanation: 'D=1-4=-3<0, x=(-1±√(-3))/2 = (-1±√3·i)/2',
  },
  {
    id: 'q023',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-6x+10=0의 두 근은?',
    options: ['3±i', '3±√10', '6±i', '-3±i'],
    answer: '3±i',
    explanation: 'D=36-40=-4, x=(6±2i)/2=3±i',
  },
  {
    id: 'q024',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-2x-3=0의 두 근은?',
    options: ['3, -1', '-3, 1', '3, 1', '-3, -1'],
    answer: '3, -1',
    explanation: '(x-3)(x+1)=0이므로 x=3 또는 x=-1',
  },
  {
    id: 'q025',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-4x+13=0의 두 근은?',
    options: ['2±3i', '4±3i', '2±√13', '-2±3i'],
    answer: '2±3i',
    explanation: 'D=16-52=-36, x=(4±6i)/2=2±3i',
  },

  // ========== 판별식 활용 ==========
  {
    id: 'q030',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-4x+k=0이 중근을 가질 때 k의 값은?',
    options: ['4', '-4', '2', '8'],
    answer: '4',
    explanation: 'D=16-4k=0, k=4',
  },
  {
    id: 'q031',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+kx+9=0이 중근을 가질 때 양수 k의 값은?',
    options: ['6', '3', '9', '12'],
    answer: '6',
    explanation: 'D=k²-36=0, k=±6이므로 양수 k=6',
  },
  {
    id: 'q032',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-2x+k=0이 서로 다른 두 실근을 가지려면?',
    options: ['k<1', 'k>1', 'k=1', 'k≤1'],
    answer: 'k<1',
    explanation: 'D=4-4k>0이면 k<1',
  },
  {
    id: 'q033',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+2x+k=0이 두 허근을 가지려면?',
    options: ['k>1', 'k<1', 'k=1', 'k≥1'],
    answer: 'k>1',
    explanation: 'D=4-4k<0이면 k>1',
  },
  {
    id: 'q034',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-6x+k=0이 중근을 가질 때 k의 값은?',
    answer: '9',
    explanation: 'D=36-4k=0, k=9',
  },
  {
    id: 'q035',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: '2x²+4x+k=0이 중근을 가질 때 k의 값은?',
    answer: '2',
    explanation: 'D=16-8k=0, k=2',
  },

  // ========== 근과 계수의 관계 응용 ==========
  {
    id: 'q040',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-3x+1=0의 두 근을 α, β라 할 때 α²+β²의 값은?',
    options: ['7', '5', '9', '11'],
    answer: '7',
    explanation: 'α+β=3, αβ=1이므로 α²+β²=(α+β)²-2αβ=9-2=7',
  },
  {
    id: 'q041',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-5x+2=0의 두 근을 α, β라 할 때 1/α+1/β의 값은?',
    options: ['5/2', '2/5', '5', '1/5'],
    answer: '5/2',
    explanation: '1/α+1/β = (α+β)/(αβ) = 5/2',
  },
  {
    id: 'q042',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-4x+2=0의 두 근을 α, β라 할 때 α²β+αβ²의 값은?',
    options: ['8', '4', '6', '2'],
    answer: '8',
    explanation: 'α²β+αβ² = αβ(α+β) = 2·4 = 8',
  },
  {
    id: 'q043',
    type: 'short',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-2x-3=0의 두 근을 α, β라 할 때 α²+β²의 값은?',
    answer: '10',
    explanation: 'α+β=2, αβ=-3이므로 α²+β²=(α+β)²-2αβ=4+6=10',
  },
  {
    id: 'q044',
    type: 'short',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²+3x+1=0의 두 근을 α, β라 할 때 (α-β)²의 값은?',
    answer: '5',
    explanation: '(α-β)²=(α+β)²-4αβ=9-4=5',
  },

  // ========== 근의 공식 (실수근) ==========
  {
    id: 'q050',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-5x+4=0의 두 근은?',
    options: ['1, 4', '-1, -4', '1, -4', '-1, 4'],
    answer: '1, 4',
    explanation: '(x-1)(x-4)=0이므로 x=1 또는 x=4',
  },
  {
    id: 'q051',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-3x-10=0의 두 근은?',
    options: ['-2, 5', '2, -5', '2, 5', '-2, -5'],
    answer: '-2, 5',
    explanation: '(x+2)(x-5)=0이므로 x=-2 또는 x=5',
  },
  {
    id: 'q052',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: '근의 공식: ax²+bx+c=0의 해는?',
    options: ['(-b±√(b²-4ac))/(2a)', '(b±√(b²-4ac))/(2a)', '(-b±√(b²+4ac))/(2a)', '(-b±√(4ac-b²))/(2a)'],
    answer: '(-b±√(b²-4ac))/(2a)',
    explanation: '근의 공식: x = (-b±√(b²-4ac))/(2a)',
  },
  {
    id: 'q053',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-2x-1=0의 두 근의 합은?',
    options: ['2', '-2', '1', '-1'],
    answer: '2',
    explanation: '두 근의 합 = 2/1 = 2 (근과 계수의 관계)',
  },

  // ========== 복소수와 이차방정식 연결 ==========
  {
    id: 'cq001',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: 'x²+x+1=0의 한 근을 ω라 할 때, ω²+ω+1은?',
    options: ['0', '1', '-1', '2'],
    answer: '0',
    explanation: 'ω가 x²+x+1=0의 근이므로 ω²+ω+1=0',
  },
  {
    id: 'cq002',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: 'i가 이차방정식 x²+bx+2=0의 한 근일 때, b의 값은?',
    options: ['0', '1', '-1', '2'],
    answer: '0',
    explanation: 'i²+bi+2=0에서 -1+bi+2=0, 1+bi=0이므로 b=0',
  },
  {
    id: 'cq003',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: '1+i가 x²+bx+c=0 (b, c는 실수)의 한 근일 때, 다른 한 근은?',
    options: ['1-i', '-1+i', '1+i', '-1-i'],
    answer: '1-i',
    explanation: '계수가 실수일 때 켤레복소수도 근이다.',
  },
  {
    id: 'cq004',
    type: 'multiple',
    category: 'concept',
    difficulty: 3,
    text: '실수계수 이차방정식이 허근을 가지면, 두 허근의 관계는?',
    options: ['서로 켤레복소수', '같은 수', '부호가 반대', '절댓값이 같음'],
    answer: '서로 켤레복소수',
    explanation: '실수계수 이차방정식의 허근은 켤레복소수 쌍으로 나타난다.',
  },

  // ========== 추가 개념 문제 ==========
  {
    id: 'ex001',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '이차방정식이란?',
    options: [
      '최고차항의 차수가 2인 방정식',
      '최고차항의 차수가 1인 방정식',
      '두 개의 근을 갖는 방정식',
      '항이 두 개인 방정식',
    ],
    answer: '최고차항의 차수가 2인 방정식',
    explanation: 'ax²+bx+c=0 (a≠0) 형태의 방정식',
  },
  {
    id: 'ex002',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '다음 중 이차방정식이 아닌 것은?',
    options: ['x²+x+1=0', 'x²-1=0', 'x²-x=0', 'x+1=0'],
    answer: 'x+1=0',
    explanation: 'x+1=0은 일차방정식이다.',
  },
  {
    id: 'ex003',
    type: 'multiple',
    category: 'concept',
    difficulty: 2,
    text: '이차방정식 ax²+bx+c=0에서 a=0이면 안 되는 이유는?',
    options: [
      '이차방정식이 되지 않기 때문',
      '근이 없기 때문',
      '판별식이 정의되지 않기 때문',
      '허근이 생기기 때문',
    ],
    answer: '이차방정식이 되지 않기 때문',
    explanation: 'a=0이면 이차항이 없어지므로 이차방정식이 아니다.',
  },
  {
    id: 'ex004',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²=9의 해는?',
    options: ['x=±3', 'x=3', 'x=-3', 'x=9'],
    answer: 'x=±3',
    explanation: 'x²=9이므로 x=3 또는 x=-3',
  },
  {
    id: 'ex005',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x²-1=0에서 양의 근은?',
    answer: '1',
    explanation: '(x-1)(x+1)=0이므로 x=1 또는 x=-1',
  },
  {
    id: 'ex006',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-6x+9=0의 해는?',
    options: ['x=3 (중근)', 'x=3 또는 x=-3', 'x=-3 (중근)', 'x=3 또는 x=9'],
    answer: 'x=3 (중근)',
    explanation: '(x-3)²=0이므로 x=3 (중근)',
  },
  {
    id: 'ex007',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+2x+1=0의 해는?',
    options: ['x=-1 (중근)', 'x=1 (중근)', 'x=-1 또는 x=1', '허근'],
    answer: 'x=-1 (중근)',
    explanation: '(x+1)²=0이므로 x=-1 (중근)',
  },
  {
    id: 'ex008',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-4x+4=0의 중근은?',
    answer: '2',
    explanation: '(x-2)²=0이므로 x=2 (중근)',
  },
  {
    id: 'ex009',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: '3x²-12=0의 두 근의 합은?',
    options: ['0', '4', '-4', '2'],
    answer: '0',
    explanation: 'x²=4이므로 x=±2, 합=0',
  },
  {
    id: 'ex010',
    type: 'short',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²-10x+25=0의 중근은?',
    answer: '5',
    explanation: '(x-5)²=0이므로 x=5',
  },
  {
    id: 'ex011',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '√(-1)은 어떤 수인가?',
    options: ['허수 단위 i', '실수', '-1', '정의되지 않음'],
    answer: '허수 단위 i',
    explanation: '√(-1)을 허수 단위 i로 정의한다.',
  },
  {
    id: 'ex012',
    type: 'multiple',
    category: 'concept',
    difficulty: 1,
    text: '복소수의 집합에 대한 설명으로 옳은 것은?',
    options: [
      '실수는 복소수이다',
      '허수는 실수이다',
      '복소수는 반드시 허수이다',
      '정수는 복소수가 아니다',
    ],
    answer: '실수는 복소수이다',
    explanation: '실수 a는 a+0i로 나타낼 수 있으므로 복소수이다.',
  },
  {
    id: 'ex013',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-3x+k=0이 서로 다른 두 실근을 가질 조건은?',
    options: ['k<9/4', 'k>9/4', 'k=9/4', 'k≤9/4'],
    answer: 'k<9/4',
    explanation: 'D=9-4k>0이면 k<9/4',
  },
  {
    id: 'ex014',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: '(3+4i)+(3-4i)의 값은?',
    options: ['6', '8i', '6+8i', '0'],
    answer: '6',
    explanation: '6 + (4-4)i = 6',
  },
  {
    id: 'ex015',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: '(3+4i)-(3-4i)의 값은?',
    options: ['8i', '6', '0', '-8i'],
    answer: '8i',
    explanation: '(3-3) + (4+4)i = 8i',
  },
  {
    id: 'ex016',
    type: 'short',
    category: 'quadratic',
    difficulty: 1,
    text: 'x(x-5)=0의 두 근의 합은?',
    answer: '5',
    explanation: 'x=0 또는 x=5, 합=5',
  },
  {
    id: 'ex017',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 3,
    text: 'x²-px+q=0의 두 근이 2, 3일 때 p-q의 값은?',
    options: ['-1', '1', '5', '-5'],
    answer: '-1',
    explanation: 'p=5 (합), q=6 (곱), p-q=5-6=-1',
  },
  {
    id: 'ex018',
    type: 'multiple',
    category: 'complex',
    difficulty: 3,
    text: '(1+i)⁴의 값은?',
    options: ['-4', '4', '4i', '-4i'],
    answer: '-4',
    explanation: '(1+i)²=2i, (2i)²=4i²=-4',
  },
  {
    id: 'ex019',
    type: 'multiple',
    category: 'complex',
    difficulty: 2,
    text: 'z=2+3i일 때 z+z̄의 값은?',
    options: ['4', '6i', '4+6i', '0'],
    answer: '4',
    explanation: 'z+z̄ = (2+3i)+(2-3i) = 4',
  },
  {
    id: 'ex020',
    type: 'multiple',
    category: 'quadratic',
    difficulty: 2,
    text: 'x²+2x-15=0의 두 근은?',
    options: ['3, -5', '-3, 5', '-3, -5', '3, 5'],
    answer: '3, -5',
    explanation: '(x+5)(x-3)=0이므로 x=-5 또는 x=3',
  },
];

export function getQuestions(count: number): Question[] {
  const shuffled = [...QUESTION_BANK].sort(() => Math.random() - 0.5);
  const picked = shuffled.slice(0, Math.min(count, QUESTION_BANK.length));
  return picked.map((q) => {
    const { text, options } = texifyQuestionFields(q.text, q.options);
    const explanation = q.explanation ? texifyQuestionFields(q.explanation).text : undefined;
    return { ...q, text, options, explanation, latex: true };
  });
}

export function getQuestionsByCategory(category: string, count: number): Question[] {
  const filtered = QUESTION_BANK.filter(q => q.category === category);
  const shuffled = filtered.sort(() => Math.random() - 0.5);
  const picked = shuffled.slice(0, count);
  return picked.map((q) => {
    const { text, options } = texifyQuestionFields(q.text, q.options);
    const explanation = q.explanation ? texifyQuestionFields(q.explanation).text : undefined;
    return { ...q, text, options, explanation, latex: true };
  });
}
